name: NASA Project CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version 18.12.1
        uses: actions/setup-node@v2
        with:
          node-version: "18.12.1"
      - run: npm install
      - run: npm run build --prefix client
